application: target-us
version: 1
runtime: python
api_version: 1

error_handlers:
  - file: error/default_error.html

builtins:
- appstats: on
- datastore_admin: on
- remote_api: on

handlers:
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
  login: admin

- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  upload: static/(.*)

- url: /static
  static_dir: static

- url: /_ah/queue/deferred
  script: main.py
  login: admin

- url: /background/.*
  script: main.py
  login: admin

- url: /.*
  script: main.py
